<h1 class="lead">Titles:</h1>
<div class="row">
    <div class="span2 well">
        <a href="title/cover/id/1">Octane</a>
        <img src="http://www.greenerideal.com/wp-content/uploads/2012/09/Costa-Rica.jpg" class="img-rounded" />
        <br />5 Issues
    </div>
    <div class="span2 well">
        <a href="title/cover/id/2">Zeitgeist</a>
        <img src="http://www.businesspundit.com/wp-content/uploads/2009/06/zzhummer.jpg" class="img-rounded" />
        <br />5 Issues
    </div>
    <div class="span2 well">
        <a href="title/cover/id/3">Kajed Flight</a>
        <img src="http://www.b-scenefilms.com/stratocaster.jpg" class="img-rounded" />
        <br />5 Issues
    </div>
    <div class="span2 well">
        <a href="title/cover/id/4">Head-off Ville</a>
        <img src="http://www.abercrombiekent.com/travel-destinations/images/Africa.jpg" class="img-rounded" />
        <br />5 Issues
    </div>
</div>