<script type="text/javascript">
    $(document).ready(function(){
        /*
        $('#login_modal').modal({
            show: false
        });
        
        $('a').click(function(e){
            $('#login_modal').modal('show');
        });
        
        $('.well img').mouseup(function(e){
            $('#login_modal').modal('show');
        });
        */
        
    });
</script>
<h1 class="lead">Your latest activity:</h1>
<div class="row">
    <div class="span2 well">
        <a href="title/cover/id/1">Octane</a>
        <img src="http://www.greenerideal.com/wp-content/uploads/2012/09/Costa-Rica.jpg" class="img-rounded" />
        <br />5 Issues
    </div>
    <div class="span2 well">
        <a href="title/cover/id/2">Zeitgeist</a>
        <img src="http://www.businesspundit.com/wp-content/uploads/2009/06/zzhummer.jpg" class="img-rounded" />
        <br />5 Issues
    </div>
    <div class="span2 well">
        <a href="title/cover/id/3">Kajed Flight</a>
        <img src="http://www.b-scenefilms.com/stratocaster.jpg" class="img-rounded" />
        <br />5 Issues
    </div>
    <div class="span2 well">
        <a href="title/cover/id/4">Head-off Ville</a>
        <img src="http://www.abercrombiekent.com/travel-destinations/images/Africa.jpg" class="img-rounded" />
        <br />5 Issues
    </div>
</div>


<!-- login modal -->
<div class="modal hide fade" id="login_modal">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    <h3>Get started</h3>
  </div>
  <div class="modal-body">
    <p>You must log in using one of your social networking accounts! ... let's say Twitter</p>
    <a class="btn btn-info">Login with Twitter</a>
    <a class="btn btn-primary">Login with Facebook</a>
  </div>
  <div class="modal-footer">
    <a href="#" class="btn" data-dismiss="modal">Close</a>
  </div>
</div>