<p>Thank you for your info request!</p>

<p><strong>Artist</strong>Controlbox is currently in beta. We look forward to working with artists and creatives on their practical needs in ironing out just the right features that you need to become a self-sustaining artist, and weed out features that are frankly pointless. So thanks again for your interest :)</p>

<p>Here is the info we received from you, which we will use to get in touch with you when we have more information and next steps on getting your website together:</p>

<strong>Name:</strong> <?=$this->signup->name?><br />
<strong>Email:</strong> <?=$this->signup->email?><br />
<strong>Website:</strong> <?=$this->signup->url?><br />
<strong>Website wishes:</strong><br />
<blockquote><pre><?=$this->signup->wishes?></pre></blockquote>

<p>Stay tuned, and we will get back to you ASAP.</p>

<p>Thanks!<br />-Rishi</p>
