<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>ArtistControlbox Admin > <?=$this->controller?> > <?=$this->action?> </title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <script src="/js/jquery.js"></script>
    <script src="/js/jquery.tmpl.js"></script>
    <script src="/js/ckeditor/ckeditor.js"></script>
    <script src="/js/ckeditor/config.js"></script>
    <script src="/js/ckeditor/lang/en.js"></script>
    <script src="/js/ckeditor/styles.js"></script>
    <script type="text/javascript">
        $(document).ajaxError(function(event, request, settings){
            console.log(event);
         });
    </script>
    <!-- Le styles -->
    <link href="/css/bootstrap.css" rel="stylesheet">
    <style>
      body {
        padding-top: 60px; /* 60px to make the container go all the way to the bottom of the topbar */
      }
    </style>
    <link href="/css/bootstrap-responsive.css" rel="stylesheet">
    <link href="/js/ckeditor/skins/kama/editor.css" rel="stylesheet">

    <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    <!-- Le fav and touch icons -->
    <link rel="shortcut icon" href="/ico/favicon.ico">
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="/ico/apple-touch-icon-144-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="/ico/apple-touch-icon-114-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="/ico/apple-touch-icon-72-precomposed.png">
    <link rel="apple-touch-icon-precomposed" href="/ico/apple-touch-icon-57-precomposed.png">
  </head>

  <body data-api-key="<?= $this->artist->api_key ?>">
    <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
            <button type="button" class="btn btn-navbar collapsed" data-toggle="collapse" data-target=".nav-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
          <a class="brand" href="/admin"><img src="/images/line_logo.png" border="0" class="pull-left" style="margin:-5px 5px 0px 0px;"> <strong>Artist</strong>Controlbox Admin</a>
          <div class="nav-collapse collapse">
            <ul class="nav" role="navigation">
                <?php if ($this->logged_in===true){ ?>
                
                
                <li <?php if(
                        $this->controller=="titles" 
                        || $this->controller=="issues" 
                        || $this->controller=="galleries" 
                        || $this->controller=="contents"
                        || $this->controller=="feeds"
                        || $this->controller=="backgrounds"
                ){?>class="active"<?php } ?>>
                <div class="btn-group">
                    <a class="btn dropdown-toggle btn-inverse" data-toggle="dropdown" href="#">
                      Content
                      <span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu">
                        <li <?php if($this->controller=="titles" || $this->controller=="issues"){?>class="active"<?php } ?>><a href="/admin/titles">Titles</a></li>
                        <li <?php if($this->controller=="galleries" || $this->controller=="contents"){?>class="active"<?php } ?>><a href="/admin/galleries">Galleries</a></li>
                        <li <?php if($this->controller=="feeds"){?>class="active"<?php } ?>><a href="/admin/feeds">Feeds</a></li>
                        <li <?php if($this->controller=="backgrounds"){?>class="active"<?php } ?>><a href="/admin/backgrounds">Backgrounds</a></li>
                    </ul>
                  </div>
                </li>
                
                
                <li <?php if($this->controller=="websites"){?>class="active"<?php } ?>>
                <div class="btn-group">
                    <a class="btn dropdown-toggle btn-inverse" data-toggle="dropdown" href="#">
                      Website
                      <span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu">
                        <li <?php if($this->controller=="websites" && $this->action==""){?>class="active"<?php } ?>><a href="/admin/websites">Settings</a></li>
                        <li <?php if($this->controller=="websites" && $this->action=="editor"){?>class="active"<?php } ?>><a href="/admin/websites/editor">Editor</a></li>
                    </ul>
                  </div>
                </li>
                
                
                <li <?php if($this->controller=="account" || $this->controller=="email"){?>class="active"<?php } ?>>
                <div class="btn-group">
                    <a class="btn dropdown-toggle btn-inverse" data-toggle="dropdown" href="#">
                      Account
                      <span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu">
                        <li <?php if($this->controller=="account"){?>class="active"<?php } ?>><a href="/admin/account">Settings</a></li>
                        <?php if($this->is_internal_admin==1){ ?>
                            <li <?php if($this->controller=="email"){?>class="active"<?php } ?>><a href="/admin/email">Email</a></li>
                        <?php } ?>
                        <li><a href="/admin/index/logout">Logout</a></li>
                    </ul>
                  </div>
                </li>
                
                <li><a><span class="label label-info"><i class="icon-user icon-white"></i> <?= $this->artist->email ?></span></a></li>
                
                
                <?php } ?>
            </ul>
              
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>
    
      <div class="row">
        <div class="span6 offset1">
        <div id="error_messages">
            <?php if(count($this->errors)>0){ ?>
              <?php foreach($this->errors as $error) { ?>
                  <?php $error = json_decode($error); ?>
                  <div class="alert alert-error">
                      <button type="button" class="close" data-dismiss="alert">×</button>
                      <strong><?= $error->field ?></strong> <?= $error->message ?>
                    </div>
              <?php } ?>
            <?php } ?>
        </div>
        <div id="success_messages">
            <?php if(count($this->success)>0){ ?>
              <?php foreach($this->success as $success) { ?>
                  <div class="alert alert-success">
                      <button type="button" class="close" data-dismiss="alert">×</button>
                      <?= $success ?>
                    </div>
              <?php } ?>
            <?php } ?>

        </div>
      </div>
    </div>
    <div class="container">
        <?php echo $this->layout()->content ?>
    </div> <!-- /container -->

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="/js/bootstrap-transition.js"></script>
    <script src="/js/bootstrap-alert.js"></script>
    <script src="/js/bootstrap-modal.js"></script>
    <script src="/js/bootstrap-dropdown.js"></script>
    <script src="/js/bootstrap-scrollspy.js"></script>
    <script src="/js/bootstrap-tab.js"></script>
    <script src="/js/bootstrap-tooltip.js"></script>
    <script src="/js/bootstrap-popover.js"></script>
    <script src="/js/bootstrap-button.js"></script>
    <script src="/js/bootstrap-collapse.js"></script>
    <script src="/js/bootstrap-carousel.js"></script>
    <script src="/js/bootstrap-typeahead.js"></script>
    <script src="/js/bootstrap-typeahead.js"></script>
    
    <!-- The jQuery UI widget factory, can be omitted if jQuery UI is already included -->
    <script src="/js/jquery.ui.widget.js"></script>
    <!-- The Templates plugin is included to render the upload/download listings -->
    <script src="http://blueimp.github.com/JavaScript-Templates/tmpl.min.js"></script>
    <!-- The Load Image plugin is included for the preview images and image resizing functionality -->
    <script src="http://blueimp.github.com/JavaScript-Load-Image/load-image.min.js"></script>
    <!-- The Canvas to Blob plugin is included for image resizing functionality -->
    <script src="http://blueimp.github.com/JavaScript-Canvas-to-Blob/canvas-to-blob.min.js"></script>
    <!-- The Iframe Transport is required for browsers without support for XHR file uploads -->
    <script src="/js/jquery.iframe-transport.js"></script>
    <!-- The basic File Upload plugin -->
    <script src="/js/jquery.fileupload.js"></script>
    <!-- The File Upload file processing plugin -->
    <script src="/js/jquery.fileupload-fp.js"></script>
    <!-- The File Upload user interface plugin -->
    <script src="/js/jquery.fileupload-ui.js"></script>
    
    <script src="/js/ZeroClipboard.min.js"></script>
    <script src="/js/jquery.timeago.js"></script>
    <script src="http://d1n0x3qji82z53.cloudfront.net/src-min-noconflict/ace.js" type="text/javascript" charset="utf-8"></script>
    
    
    <!-- jQuery UI -->
    <script src="/js/jquery-ui-1.10.0.custom.min.js"></script>
    
    <!-- Logout: <?php echo date("F j, Y g:i:s a", $_SESSION['__ZF']['ActionPulp']['ENT']); ?> -->
  </body>
</html>
