<script type="text/javascript">
    $(document).ready(function(){
        CKEDITOR.replace( 'description', {
            width: 600
        });
    });
</script>
<ul class="breadcrumb">
    <li><a>Content</a> <span class="divider">></span></li>
    <li><a href="/admin/galleries">Galleries</a> <span class="divider">></span></li>
    <li class="active"><?= $this->gallery->name ?></li>
</ul>
<div class="row">
    <form class="form-horizontal" id="the_form" action="/admin/galleries/details/id/<?= $this->id ?>" method="POST" enctype="multipart/form-data">
      <div class="control-group">
        <label class="control-label" for="sort_order">Sort Order</label>
        <div class="controls">
            <div class="input-prepend">
                <span class="add-on">#</span><input type="text" name="sort_order" id="sort_order" placeholder="Sort Order" value="<?= $this->gallery->sort_order ?>" class="input-mini">
            </div>
        </div>
      </div>
      <div class="control-group">
        <label class="control-label" for="name">Name</label>
        <div class="controls">
          <input type="text" name="name" id="name" placeholder="Name" value="<?= $this->gallery->name ?>">
        </div>
      </div>
      <div class="control-group">
        <label class="control-label" for="description">Description</label>
        <div class="controls">
            <textarea id="description" name="description"><?= $this->gallery->description ?></textarea>
        </div>
      </div>
      <div class="control-group">
        <label class="control-label" for="type">Type</label>
        <div class="controls">
            <select name="type" id="type">
                <option value="image" <?= $this->gallery->type=="image"?"selected":null ?>>Image</option>
                <option value="audio" <?= $this->gallery->type=="audio"?"selected":null ?>>Audio</option>
                <option value="video" <?= $this->gallery->type=="video"?"selected":null ?>>Video</option>
                
            </select>
        </div>
      </div>
      <div class="control-group">
        <label class="control-label" for="status">Status</label>
        <div class="controls">
            <select name="status" id="status">
                <option value="enabled" <?= $this->gallery->status=="enabled"?"selected":null ?>>Enabled</option>
                <option value="disabled" <?= $this->gallery->status=="disabled"?"selected":null ?>>Disabled</option>
            </select>
        </div>
      </div>
      <div class="control-group">
        <div class="controls">
          <button type="submit" class="btn btn-primary">Save</button>
          <a href="/admin/galleries" class="btn">Cancel</a>
        </div>
      </div>
    </form>
</div>
